version: "3.8"
services:
  app:
    container_name: app
    image: user_api:tag 394650570520.dkr.ecr.us-east-1.amazonaws.com/jennycj-bfree-challenge:latest
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./users:/data/db
    ports:
      - "27017:27017"
