version: "3.8"
services:
  app:
    container_name: app
    image: user_api:tag ${{ secrets.ECR_REPOSITORY }}
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./users:/data/db
    ports:
      - "27017:27017"
