name: Docker Image CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr-web-image
        IMAGE_TAG_1: ${{ env.APP_IMAGE }}
        IMAGE_TAG_2: ${{ env.MONGO_IMAGE }}
      run: |
        docker compose up
        docker tag $IMAGE_TAG_1 $ECR_REGISTRY/$ECR_REPOSITORY
        docker tag $IMAGE_TAG_2 $ECR_REGISTRY/$ECR_REPOSITORY
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_1
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_2
